from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 800)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainHLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.mainHLayout.setContentsMargins(10, 10, 10, 10)
        self.mainHLayout.setSpacing(10)
        self.leftPanel = QtWidgets.QWidget()
        self.leftPanel.setFixedWidth(270)
        self.leftVLayout = QtWidgets.QVBoxLayout(self.leftPanel)
        self.leftVLayout.setContentsMargins(0, 0, 0, 0)
        self.leftVLayout.setSpacing(6)
        self.label = QtWidgets.QLabel("FUNCTIE")
        self.leftVLayout.addWidget(self.label)
        self.FunctieCamp = QtWidgets.QLineEdit()
        self.FunctieCamp.setObjectName("FunctieCamp")
        self.leftVLayout.addWidget(self.FunctieCamp)
        self.hFisier = QtWidgets.QHBoxLayout()
        self.label_10 = QtWidgets.QLabel("FISIER")
        self.hFisier.addWidget(self.label_10)
        self.Incarca = QtWidgets.QPushButton("INCARCA")
        self.Incarca.setObjectName("Incarca")
        self.hFisier.addWidget(self.Incarca)
        self.leftVLayout.addLayout(self.hFisier)
        self.label_5 = QtWidgets.QLabel("INTERVAL")
        self.leftVLayout.addWidget(self.label_5)
        self.formLayout = QtWidgets.QFormLayout()
        self.label_3 = QtWidgets.QLabel("a")
        self.ACamp = QtWidgets.QLineEdit()
        self.ACamp.setObjectName("ACamp")
        self.formLayout.addRow(self.label_3, self.ACamp)
        self.label_4 = QtWidgets.QLabel("b")
        self.BCamp = QtWidgets.QLineEdit()
        self.BCamp.setObjectName("BCamp")
        self.formLayout.addRow(self.label_4, self.BCamp)
        self.leftVLayout.addLayout(self.formLayout)
        self.label_6 = QtWidgets.QLabel("NUMAR ITERATII")
        self.leftVLayout.addWidget(self.label_6)
        self.NrIteratiiCamp = QtWidgets.QLineEdit()
        self.NrIteratiiCamp.setObjectName("NrIteratiiCamp")
        self.leftVLayout.addWidget(self.NrIteratiiCamp)
        self.label_7 = QtWidgets.QLabel("TIP PRECIZIE")
        self.leftVLayout.addWidget(self.label_7)
        self.hRadio = QtWidgets.QHBoxLayout()
        self.RadioIteratii = QtWidgets.QRadioButton("INTRE ITERATII")
        self.RadioIteratii.setObjectName("RadioIteratii")
        self.hRadio.addWidget(self.RadioIteratii)
        self.RadioZecimale = QtWidgets.QRadioButton("NUMAR ZECIMALE")
        self.RadioZecimale.setObjectName("RadioZecimale")
        self.hRadio.addWidget(self.RadioZecimale)
        self.leftVLayout.addLayout(self.hRadio)
        self.TolerantaText = QtWidgets.QLabel("TOLERANTA (Epsilon)")
        self.TolerantaText.setObjectName("TolerantaText")
        self.leftVLayout.addWidget(self.TolerantaText)
        self.TolerantaCamp = QtWidgets.QLineEdit()
        self.TolerantaCamp.setObjectName("TolerantaCamp")
        self.leftVLayout.addWidget(self.TolerantaCamp)
        self.ZecimaleText = QtWidgets.QLabel("NUMAR DE ZECIMALE EXACTE")
        self.ZecimaleText.setObjectName("ZecimaleText")
        self.leftVLayout.addWidget(self.ZecimaleText)
        self.ZecimaleCamp = QtWidgets.QLineEdit()
        self.ZecimaleCamp.setObjectName("ZecimaleCamp")
        self.leftVLayout.addWidget(self.ZecimaleCamp)
        self.label_2 = QtWidgets.QLabel("TIP EROARE")
        self.leftVLayout.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox()
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItems(["Absoluta", "Relativa", "Ambele"])
        self.leftVLayout.addWidget(self.comboBox)
        self.Itereaza = QtWidgets.QPushButton("ITEREAZA!")
        self.Itereaza.setObjectName("Itereaza")
        self.leftVLayout.addWidget(self.Itereaza)
        self.label_rez = QtWidgets.QLabel("")
        self.label_rez.setObjectName("label_rez")
        self.label_rez.setWordWrap(True)
        self.leftVLayout.addWidget(self.label_rez)
        self.inapoibtn = QtWidgets.QPushButton("Inapoi")
        self.inapoibtn.setObjectName("inapoibtn")
        self.leftVLayout.addWidget(self.inapoibtn)
        self.leftVLayout.addStretch()
        self.mainHLayout.addWidget(self.leftPanel)
        self.rightPanel = QtWidgets.QWidget()
        self.rightVLayout = QtWidgets.QVBoxLayout(self.rightPanel)
        self.rightVLayout.setContentsMargins(0, 0, 0, 0)
        self.rightVLayout.setSpacing(8)
        self.topRowWidget = QtWidgets.QWidget()
        self.topRowHLayout = QtWidgets.QHBoxLayout(self.topRowWidget)
        self.topRowHLayout.setContentsMargins(0, 0, 0, 0)
        self.topRowHLayout.setSpacing(8)
        self.eroriGroupBox = QtWidgets.QGroupBox("Erori")
        self.eroriVLayout = QtWidgets.QVBoxLayout(self.eroriGroupBox)
        self.SalveazaGrafic = QtWidgets.QPushButton("SALVEAZA GRAFIC ERORI")
        self.SalveazaGrafic.setObjectName("SalveazaGrafic")
        self.eroriVLayout.addWidget(self.SalveazaGrafic)
        self.verticalLayout_2 = self.eroriVLayout
        self.topRowHLayout.addWidget(self.eroriGroupBox, stretch=1)
        self.animGroupBox = QtWidgets.QGroupBox("Animatie")
        self.animVLayout = QtWidgets.QVBoxLayout(self.animGroupBox)
        self.animBtnRow = QtWidgets.QHBoxLayout()
        self.START = QtWidgets.QPushButton("START")
        self.START.setObjectName("START")
        self.animBtnRow.addWidget(self.START)
        self.STOP = QtWidgets.QPushButton("STOP")
        self.STOP.setObjectName("STOP")
        self.animBtnRow.addWidget(self.STOP)
        self.SalveazaAnim = QtWidgets.QPushButton("SALVEAZA")
        self.SalveazaAnim.setObjectName("SalveazaAnim")
        self.animBtnRow.addWidget(self.SalveazaAnim)
        self.animVLayout.addLayout(self.animBtnRow)
        self.verticalLayout_3 = self.animVLayout
        self.topRowHLayout.addWidget(self.animGroupBox, stretch=1)
        self.rightVLayout.addWidget(self.topRowWidget, stretch=1)
        self.functieGroupBox = QtWidgets.QGroupBox("Grafic Functie")
        self.functieVLayout = QtWidgets.QVBoxLayout(self.functieGroupBox)
        self.functiegraficbtn = QtWidgets.QPushButton("SALVEAZA GRAFIC FUNCTIE")
        self.functiegraficbtn.setObjectName("functiegraficbtn")
        self.functieVLayout.addWidget(self.functiegraficbtn)
        self.verticalLayout_4 = self.functieVLayout
        self.rightVLayout.addWidget(self.functieGroupBox, stretch=1)
        self.mainHLayout.addWidget(self.rightPanel, stretch=1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        MainWindow.setStatusBar(self.statusbar)
        MainWindow.setWindowTitle("Metoda_Bisectiei")
        QtCore.QMetaObject.connectSlotsByName(MainWindow)